services:
  postgres:
    image: postgres:17-alpine
    container_name: inovabank-postgres
    environment:
      POSTGRES_DB: InovaBankDb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:latest
    container_name: inovabank-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: inovabank-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: inovabank-redis
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT_PATH: InovaBank.Api
    container_name: inovabank-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - PROJECT_DLL=InovaBank.Api.dll
      - ConnectionStrings__Postgres=Host=postgres;Database=InovaBankDb;Username=admin;Password=password
      - ConnectionStrings__Redis=redis:6379
      - ConnectionStrings__MongoDb=mongodb://mongodb:27017
      - ConnectionStrings__RabbitMq=amqp://guest:guest@rabbitmq:5672
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_started
      mongodb:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started

  worker:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT_PATH: InovaBank.Worker
    container_name: inovabank-worker
    environment:
      - PROJECT_DLL=InovaBank.Worker.dll
      - ConnectionStrings__MongoDb=mongodb://mongodb:27017
      - ConnectionStrings__RabbitMq=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq
      - mongodb

volumes:
  postgres_data:
  mongo_data:
  rabbitmq_data:
