<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-InovaBank.Worker-e8fd1a38-ed99-447e-bcb2-901029a83331</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit" Version="8.2.5" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.2.5" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.4" />
    <PackageReference Include="MongoDB.Driver" Version="3.7.1" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\InovaBank.Application\InovaBank.Application.csproj" />
    <ProjectReference Include="..\InovaBank.Infrastructure\InovaBank.Infrastructure.csproj" />
  </ItemGroup>
</Project>
